name: flutter_markdown
description: A Markdown renderer for Flutter.
homepage: https://github.com/flutter/flutter_markdown
version: 0.4.3

dependencies:
  flutter:
    sdk: flutter
  markdown: ^2.1.3
  meta: ^1.1.7
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

flutter:
  assets:
    - assets/logo.png
